### ISSUE TITLE
Nginx Ingress Issues

### ISSUE THREAD

**Issue by DevOps-Dad** [kubevious/helm#12]
I am having an issue getting the UI working in my cluster.  I am running in GCP and already have an nginx ingress that I am trying to re-use for Kubevious.  I can get Kubevious to create its own ingress which creates a new GCP load balancer but I can't seem to get it to use the existing nginx.

I have added this to my ingress:
  - host: kubevious.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubevious-ui-clusterip
          servicePort: 80

I have tried several installation options but here is where I am right now:
helm upgrade --atomic -i -n kubevious \
    --version 0.8.15 \
    --set ingress.domain=example.com \
    kubevious kubevious/kubevious

When hitting the URL I get a 503 Service Temporarily Unavailable from nginx.  I'm sure this is something silly I am overlooking.

Any assistance would be greatly appreciated.

**Comment by rubenhak** [comment]
@DevOps-Dad, before we get into ingress and nginx, can you confirm that Kubevious is accessible through port mapping?

Lets try this first:
```
kubectl port-forward $(kubectl get pods -n kubevious -l "app.kubernetes.io/component=kubevious-ui" -o jsonpath="{.items[0].metadata.name}") 8080:80 -n kubevious  
```

and then access it from here http://localhost:8080

**Comment by DevOps-Dad** [comment]
Yes, that works perfectly, ensuring the problem is most likely purely with me :-)

**Comment by rubenhak** [comment]
@DevOps-Dad, thats hard to tell right now, can you join the slack channel to debug this further?

**Comment by kubevious** [comment]
Caused my misconfiguration. Closing.
