### ISSUE TITLE
BUG: mysql ReadinessProbe and LivenessProbe fail

### ISSUE THREAD

**Issue by christianhuth** [kubevious/helm#14]
`Readiness probe failed: mysql: [Warning] Using a password on the command line interface can be insecure. ERROR 1045 (28000): Access denied for user 'UNKNOWN_USER'@'localhost' (using password: YES) `

**Comment by rubenhak** [comment]
@christianknell, please see my comment in the PR.

**Comment by kubevious** [comment]
Thanks for reporting. The helm chart had been modified with various options regarding MySQL deployment. Please feel free to let us know how it works!

```sh
kubectl create namespace kubevious

helm repo add kubevious https://helm.kubevious.io

helm repo update

helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.9.27 -n kubevious
```

For more details on installation options, visit [Deployment Repository](https://github.com/kubevious/helm).

**Comment by Diliz** [comment]
Hello!

I still encounter this issue on 1.0.10 :/

**Comment by rubenhak** [comment]
@Diliz, we need some details. Could you provide logs for MySQL pod, are the PVC/PV properly bound? Any error events on them? Is there enough space available on the volume?
