### ISSUE TITLE
Unused fields from mysql.external 

### ISSUE THREAD

**Issue by garygan89** [kubevious/helm#19]
It looks like the helm chart do not use any of the fields under `mysql.external` to allow kubevious to connect to already existed mySQL deployment. Even with that flag set to `enabled` and provided all the mysql auth credentials, the deployment will still create the `mysql` pod.
```
NAME                                    READY   STATUS    RESTARTS   AGE
pod/kubevious-6d4d4c94f5-nvl6v          1/1     Running   0          8m21s
pod/kubevious-mysql-0                   1/1     Running   0          8m21s
pod/kubevious-parser-75c6f7d65d-rbfcc   1/1     Running   0          8m21s
pod/kubevious-ui-5856b6b864-bqqfd       1/1     Running   0          8m21s
```

Following is a quick grep for the `external.` key.
```
~/helm$ grep -r external.
README.md:| mysql.external.enabled | Indicates whether an existing MySQL database should be used. When enabled a new MySQL database would not be deployed. | false |
README.md:| mysql.external.host | Host for external MySQL server | |
README.md:| mysql.external.port | Port for external MySQL server | |
README.md:| mysql.external.database | Database name for external MySQL server. The database should be manually created. | |
README.md:| mysql.external.user | User name. User should have access to the database specified above. | |
README.md:| mysql.external.password | Password. | |
kubernetes/values.yaml:  external:

```

**Comment by rubenhak** [comment]
hi @garygan89, looks like we started with readme and forgot to implement :)

Can you try this when the most resent version and let me know how it works?

```
helm upgrade --atomic -i -n kubevious \
    --version  0.9.13 \
    --set mysql.external.enabled=true \
    --set mysql.external.host=the-host \
    --set mysql.external.port=the-port \
    --set mysql.external.user=the-user \
    --set mysql.external.password=the-password \
    kubevious kubevious/kubevious
```

**Comment by garygan89** [comment]
Hi @rubenhak , it works with the latest version 0.9.13, with the manifest will now set the MYSQL ENV and not creating mysql pod. Combined this with mySQL cluster setup using Bitnami [mySQL-helm](https://github.com/bitnami/charts/tree/master/bitnami/mysql), and they were a perfect match. Next step is for me to add `nodeAffinity` so that only one instance is scheduled per node.

I can now scale kubevious out without having to concern about the state since mySQL replica will handle it.

**Comment by rubenhak** [comment]
@garygan89, great that it worked out.

Just want to give you a heads up that running more than 1 replica for `kubevious` or `parser` pods would cause improper behavior.
