### ISSUE TITLE
Support ingress v1

### ISSUE THREAD

**Issue by eddycharly** [kubevious/helm#20]
As of k8s 1.22 ingress is only available in v1.
It would be nice to add support for it.

**Comment by kubevious** [comment]
Thanks for reporting. This issue has been resolved in the latest version 🎉🎉🎉.
Please let us know how it works!

```sh
kubectl create namespace kubevious

helm repo add kubevious https://helm.kubevious.io

helm repo update

helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.9.27 -n kubevious
```

For more details on installation options, visit [Deployment Repository](https://github.com/kubevious/helm).
