### ISSUE TITLE
Kindly update the mysql version as 8.0.22 not available any more

### ISSUE THREAD

**Issue by msaraya** [kubevious/helm#26]
Kindly update the mysql version as 8.0.22 is not available anymore suggesting to change it to 8.0.30
https://github.com/kubevious/helm/blob/e778006acdbf29609008fd89e34b1bde00e28e50/kubernetes/values.yaml#L209

**Comment by rubenhak** [comment]
@msaraya, mysql is updated to latest version 8.0.30. Please give it a try using:
```sh
helm upgrade --atomic -i kubevious kubevious/kubevious --version 1.0.11 -n kubevious
```
