### ISSUE TITLE
Support TLS for Ingress

### ISSUE THREAD

**Issue by cfarrend** [kubevious/helm#3]
Hey guys,

Thanks for looking into the annotations for ingress. With the testing I ran into an issue where using a custom host name you will always get the default 404 backend. For our ingresses, we need to use `tls` in order to get it to work properly.

For our fix we edited the ingress and added the following stanza:
```yaml
tls:
  - hosts:
    - example.com
    secretName: kubevious-tls
```

Again, would most likely be an optional parameter to add your `tls` in with some default values.

Examples:
https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-master-ingress.yaml#L33
https://github.com/helm/charts/blob/master/stable/mediawiki/templates/ingress.yaml#L31
https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/ingress.yaml#L18

Reference:
https://github.com/kubernetes/ingress-nginx/issues/3971

**Comment by rubenhak** [comment]
Hi @cfarrend, thanks for example and references. Could you try this out?
```sh
helm repo add kubevious https://helm.kubevious.io

helm upgrade --atomic -i kubevious kubevious/kubevious \
    --version 0.5.2 \
    --namespace kubevious \
    --set ingress.enabled=true \
    --set ingress.domain=example.com \
    --set ingress.tls=true \
    --set ingress.tlsSecretName=kubevious-tls
```

**Comment by cfarrend** [comment]
Thank you @rubenhak works perfectly 👌 

You may want to check for the existence of `ingress.tlsSecretName` then you don't need to set `ingress.tls=true`

**Comment by rubenhak** [comment]
@cfarrend, thanks. Next release will just rely on **tlsSecretName**.
