### ISSUE TITLE
unable to change the storage class of mysql 

### ISSUE THREAD

**Issue by obeyler** [kubevious/helm#4]
There is no way in current release to change the storage class of the PVC created for the Mysql include inside of kubevious.
If no storageclass default is defined in a K8S the deployment failed as the PVC stays in pending mode
![image](https://user-images.githubusercontent.com/23224162/78902612-4cb8ce00-7a7a-11ea-8a12-8a95fc9f108d.png)

**Comment by rubenhak** [comment]
@obeyler, thank you for submitting the issue and the solution!
