### ISSUE TITLE
storageClass set, PVC pending

### ISSUE THREAD

**Issue by var-log-skynet** [kubevious/helm#6]
If I set the storage class like this:
` helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.5.9 -n kubevious --set mysql.storageClass=slow`

I would expect the pv to be created and pvc bound to it. But this happens: 

```
kubectl describe pvc -n kubevious
Name:          data-kubevious-mysql-0
Namespace:     kubevious
StorageClass:
Status:        Pending
Volume:
Labels:        k8s-app=kubevious-mysql
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    kubevious-mysql-0
Events:
  Type    Reason         Age                        From                         Message
  ----    ------         ----                       ----                         -------
  Normal  FailedBinding  4m54s (x16624 over 2d21h)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```
Am I missing something?

**Comment by rubenhak** [comment]
Could you query the Statefulset **kubevious-mysql** like this:
```
kubectl get statefulset kubevious-mysql -n kubevious -o yaml
```

is there any chance you did the deployment once without setting the class and the persistent volume got created with the default storage class?

**Comment by var-log-skynet** [comment]
This is a new new deployment, so there is no statefulset to query. Also there is no existing pv. I have a glusterfs cluster with dynamic provisioning, so the pvc with a named storageclass should be sufficient to create the pv (?). Doesn't the meassage `no persistent volumes available for this claim and no storage class is set` indicate, that the  `-set mysql.storageClass=slow` parameter is not being passed?

**Comment by kubevious** [comment]
> This is a new new deployment, so there is no statefulset to query. Also there is no existing pv. I have a glusterfs cluster with dynamic provisioning, so the pvc with a named storageclass should be sufficient to create the pv (?). Doesn't the meassage `no persistent volumes available for this claim and no storage class is set` indicate, that the `-set mysql.storageClass=slow` parameter is not being passed?

There should be StatefulSet created, because the **data-kubevious-mysql-0** PVC is created because of the **volumeClaimTemplates** setting. See here: 
https://github.com/kubevious/helm/blob/master/kubernetes/templates/mysql/statefulset.yaml#L80-L91

For debugging you issue we first need to make sure that the **mysql.storageClass=slow** setting was indeed applied to the StatefulSet.

**Comment by rubenhak** [comment]
@leftbrake, sometimes such issues are easier to debug in a Slack channel. Feel free to join if we don't find a solution quickly here.

**Comment by var-log-skynet** [comment]
Thank you for your feedback! I managed to get around this by setting the glusterfs storage (named slow) as default, and then issuing the original command without setting the storageclass. This is however just a workaround, someone having multiple storageclasses might experience the same. 

Btw. the statefulsets had always been created during the previous attempts (when setting the storagecalss name), but they had always stayed in a pending state, and then had been deleted (because of the `--atomic` switch)
