### ISSUE TITLE
cluster domain is hardcoded

### ISSUE THREAD

**Issue by srgvg** [kubevious/helm#8]
The default cluster domain `cluster.local` is hardcoded in the templates.
This breaks deployment on clusters where this domain was customized.
The frontend ui shoiws an unmeaningfull 502 erro.
The ui pods logs a message like

```
2020/07/05 13:16:27 [error] 13#13: *4 kubevious-svc.kubevious.svc.cluster.local could not be resolved (3: Host not found), client: 127.0.0.1, server: , request: "GET /socket/?EIO=3&transport=polling&t=NCV7km9 HTTP/1.1", host: "localhost:3000", referrer: "http://localhost:3000/?tme=false&tmdt=U3VuIEp1bCAwNSAyMDIwIDE1OjE2OjA5IEdNVCswMjAwIChDZW50cmFsIEV1cm9wZWFuIFN1bW1lciBUaW1lKQ==&tmd=MjQ=&tmdaf=U2F0IEp1bCAwNCAyMDIwIDE1OjE2OjA5IEdNVCswMjAwIChDZW50cmFsIEV1cm9wZWFuIFN1bW1lciBUaW1lKQ=="
```

If you just leave out the `cluster.local` part, Kubernetes DNS resolving will find the right ip without you needing to know the cluster domain name.

**Comment by rubenhak** [comment]
@srgvg, we are using following signature: 
```
{{ .Values.kubevious.svcName }}.{{ .Release.Namespace }}.svc.cluster.local
```
Do you think it would be best to allow customization to `cluster.local` or the entire `svc.cluster.local` suffix?

**Comment by rubenhak** [comment]
@srgvg, we are using nginx for the frontend which tries to resolve the backend host. Without FQDN the resolution failed. For that purpose we kept `cluster.local` as the default cluster domain, but added **cluster.domain** to allow customization.

Could you try deployment with this command:
```
helm upgrade --atomic -i -n kubevious \
    --version 0.6.36 \
    --set cluster.domain=my-cluster.example \
    kubevious kubevious/kubevious
```

**Comment by srgvg** [comment]
Yep, that works flawlessly now! Thank you.

**Comment by rubenhak** [comment]
perfect. thanks for raising the issue.
